### Register User API
POST http://localhost:3003/user/register
Content-Type: application/json

{
    "username": "Developer AbdulRaheem",
    "email": "davidkanyiri@outlook.com",
    "password": "1234davy"
}

### Login User API
POST http://localhost:3003/user/login 
Content-Type: application/json

{
 "email": "davidkanyiri@outlook.com",
    "password": "1234davy"
}

### Create house API
POST http://localhost:3003/house/newHouse/
Content-Type: application/json

{
"name":"Brownstone Phase2",
"cost":14000,
"description":"spacious One bedrooms with swimming pool",
"location":"Kamuru",
"images":["https://house.jpg","house2.jpg"]
}



###GET ALL HOUSES API
GET http://localhost:3003/house/allhouses/?page=1&limit=2
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlka2FueWlyaUBvdXRsb29rLmNvbSIsImlhdCI6MTcxMjgyNzY5MH0.6_HWeXs7rV1LbzcEKgTt-pQiXdWnIxHaNgvchyOQbQQ

