### Register User API
POST http://localhost:3003/user/register
Content-Type: application/json

{
    "username": "davydo",
    "email": "dave@gmail.com",
    "role":"landlord",
    "password": "1234davy"
}

### Login User API
POST http://localhost:3003/user/login 
Content-Type: application/json

{
 "email": "dave@gmail.com",
    "password": "1234davy"
}


###De-activate User Account API

PUT http://localhost:3003/user/deactivate/6618e71b29af153c4058a933
Content-Type: application/json

### Create house API
POST http://localhost:3003/house/newHouse/
Content-Type: application/json

{
"name":"Bethsaida",
"cost":21000,
"description":"Well constructed 1 bedrooms for family",
"location":"Lower Kabete",
"images":["https://cdn.pixabay.com/photo/2016/09/19/17/16/beautiful-home-1680793_640.jpg","house2.jpg"]
}



###GET ALL HOUSES API
GET http://localhost:3003/house/allhouses
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmVAZ21haWwuY29tIiwiaWF0IjoxNzEzODU4MTg5fQ.6R1KIRJbBAc-sYYeyBZkb7WZglnrlSc8xY_RDmNM8zk


###DELETE A HOUSE
DELETE http://localhost:3003/house/remove/65faafdaf34cb55eb2bc2eda
Content-Type: application/json



###Update house details API 
PUT http://localhost:3003/house/updateHouse/65fab06ff34cb55eb2bc2edd
Content-Type: application/json
userId:6618fe685380540cb07b043d



{
    "name":"Epic gathiga Ridge",
    "cost":21000,
    "description":"Well constructed 1 bedrooms for family and single family"
}