### Register User API
POST http://localhost:3003/user/register
Content-Type: application/json

{
    "username": "Johnt",
    "email": "davidmunyiri34@gmail.com",
    "password": "1234davy"
}

### Create house API
POST http://localhost:3003/house/newHouse/
Content-Type: application/json

{
"name":"Kitisuru Cottages",
"cost":21000,
"description":"Well constructed 2 bedrooms for family",
"location":"Wangige",
"images":["https://cdn.pixabay.com/photo/2016/09/19/17/16/beautiful-home-1680793_640.jpg","house2.jpg"]
}



###GET ALL HOUSES API
GET http://localhost:3003/house/allhouses
Content-Type: application/json

